### ISSUE TITLE
container_names split does not work for LSIO container image names

### ISSUE THREAD

**Issue by thomascwells** [RealOrangeOne/docker-db-auto-backup#27]
I've been trying to get my home lab configured using Ansible, which I'm closely modeling after your wonderful infrastructure repo. I've been able to teach myself Ansible over the past couple months thanks to you and IronicBadger, and now have LISO SWAG with several other services running on my RaspberryPi. Thanks for all your work! 

I've now encountered an issue with `db-auto-backup.py` which I believe is due to slight differences in the naming of my database images vs yours. 

Your [Mariadb database image](https://github.com/RealOrangeOne/infrastructure/blob/c7d5056f2aa56113c4ca99b2387d301c630d3545/ansible/roles/pve_docker/files/nextcloud/docker-compose.yml#L34) for Nextcloud is `mariadb:10.5` while mine is `lscr.io/linuxserver/mariadb:latest`. 

I'm still quite new to Python, but as best I can tell, the the [`rsplit()` call in line 71](https://github.com/RealOrangeOne/docker-db-auto-backup/blob/28441255393576caf44f9616d656ed8486624e66/db-auto-backup.py#L71) is producing `['mariadb']` for your image name, while mine is returning `['lscr.io/linuxserver/mariadb']`, which of course can't be found in the `get_backup_method()` lookup step. 

I don't think the fix here is too complicated, and I'm happy to put together a pull request (if you want), but I don't know which solution would be preferable: 

1) use the `container.name` property instead of `container.image.tags`. Avoids the need for the `rsplit` but breaks if containers are not named correctly. 
2) more advanced string-splitting to pull the database type out of the longer image names. 
3) more advanced lookup or string matching within the `get_backup_method` definition.

**Comment by RealOrangeOne** [comment]
I built this with the idea that using non-standard database containers should be possible, and it appears I promptly didn't do anything about it...

I think the solution here is actually already implemented, mostly. `BACKUP_MAPPING`'s keys support glob-style syntax for pattern matching. Using `*` will match anything on the beginning. The problem with this is we'd need to make sure other containers aren't matched.

Perhaps instead we should more explicitly add support for LSIO containers, by adding extra values into `BACKUP_MAPPING` for `*/linuxserver/mariadb`? That feels like the solution which is going to break the fewest existing setups.

**Comment by thomascwells** [comment]
Thanks for the reply! Sorry for the delay. [insert here standard excuses about day jobs and side projects]

So, I think you're suggesting update BACKUP_MAPPING to look something like this? 

```python
BACKUP_MAPPING: Dict[str, BackupCandidate] = {
    "postgres": backup_psql,
    "mysql": backup_mysql,
    "mariadb": backup_mysql, 
    "*/linuxserver/mariadb": backup_mysql
}
```

Seems like it should work. I'll give that a test on my setup and report back.

**Comment by DecWebb** [comment]
any updates on this?

**Comment by thomascwells** [comment]
Good question. No, it looks like I haven't implemented this test yet in my setup. It's still on my to-do list.
