### ISSUE TITLE
Support for nextcloud AIO postgres image

### ISSUE THREAD

**Issue by kzshantonu** [RealOrangeOne/docker-db-auto-backup#57]
Would be nice. It's just postgres https://hub.docker.com/r/nextcloud/aio-postgresql

**Comment by RealOrangeOne** [comment]
I'm not very familiar with Nextcloud AIO - I thought it all ran in a single container.

It looks like it's just based on the postgres container, with a little extra configuration - is that right? If you have `$POSTGRES_USER` set, it ought to be very simple to add support, so long as `pgdump` in the available too.

**Comment by kzshantonu** [comment]
Yes it's just like the original postgres image.
<img width="429" alt="WindowsTerminal_dteCMZ4iW8" src="https://github.com/RealOrangeOne/docker-db-auto-backup/assets/7745374/92138bb2-7506-439f-b208-1000a90c8e4b">

**Comment by kzshantonu** [comment]
This one used by immich would also be handy `tensorchord/pgvecto-rs`

**Comment by RealOrangeOne** [comment]
Adding support for those ought to be quite simple, as they both look and act like regular postgres containers. Fancy posting a PR?

**Comment by kzshantonu** [comment]
Sure, I'm not good with python but I tried: https://github.com/RealOrangeOne/docker-db-auto-backup/pull/58
