### ISSUE TITLE
Feature: Back up custom database containers

### ISSUE THREAD

**Issue by vahidalvandi** [RealOrangeOne/docker-db-auto-backup#64]
How should I set it to backup from mysql?
Can the backup time be set?

**Comment by RealOrangeOne** [comment]
MySQL is one of the supported engines, so so long as the database container is running, it should be discovered and backed up. Is your container not being detected?

As for the schedule, this can be configured using the `$SCHEDULE` environment variable, to run at any time of the week. See the README for further details on that and the format.

**Comment by vahidalvandi** [comment]
i have redis and mysql containers together,  But he only took a backup of cb-redis-1.rdb from redis and did not take a backup of mysql

**Comment by RealOrangeOne** [comment]
Which mysql container are you using? Have you looked at the logs for `docker-db-auto-backup` to see if there were any errors?

**Comment by vahidalvandi** [comment]
> Which mysql container are you using? Have you looked at the logs for `docker-db-auto-backup` to see if there were any errors?

FROM mysql/mysql-server:8.0

**Comment by RealOrangeOne** [comment]
> FROM

Does this mean you're building a custom container for `mysql`? The container uses the tagged name of the container image to detect how to back it up. If it has a name it's not expecting, it won't work.

**Comment by vahidalvandi** [comment]
Only the name of the service has been changed to db. How can this be done?

**Comment by RealOrangeOne** [comment]
The image seems to be `docker-db`, which is the name, which isn't supported. Do you need a custom container or could you just use `mysql/mysql-server:8.0` directly?

Currently, there's no way to force the backup mechanism for an unknown container, but I'd welcome a PR to add that functionality!

**Comment by vahidalvandi** [comment]
i chaned docker-db to mysql/mysql-server:8.0 but not worked

```
CONTAINER ID   IMAGE                                         COMMAND                  CREATED        STATUS                  PORTS                                                                                         NAMES
ff0ecdc9e525   docker-web                                    "caddy run --config …"   17 hours ago   Up 17 hours             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 443/udp, 2019/tcp   docker-web-1
2bbe8185e817   docker-app                                    "docker-php-entrypoi…"   17 hours ago   Up 17 hours             9000/tcp                                                                                      docker-app-1
5ad3e8df4134   mysql/mysql-server:8.0                        "/entrypoint.sh mysq…"   17 hours ago   Up 17 hours (healthy)   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060-33061/tcp                                    docker-db-1
a78658172b6c   ghcr.io/realorangeone/db-auto-backup:latest   "python3 ./db-auto-b…"   17 hours ago   Up 17 hours                                                                                                           docker-backup-1
6ca016492d21   redis:6.2-alpine                              "docker-entrypoint.s…"   17 hours ago   Up 17 hours             6379/tcp                                                                                      docker-redis-1
11242b794bd5   getmeili/meilisearch:v1.5                     "tini -- /bin/sh -c …"   17 hours ago   Up 17 hours             0.0.0.0:7700->7700/tcp, :::7700->7700/tcp
```

**Comment by RealOrangeOne** [comment]
[`mysql/mysql-server`](https://hub.docker.com/r/mysql/mysql-server) I agree does seem to be a container which isn't picked up.

However, it looks like those containers haven't been updated in "a year", so I'd recommend moving away to the [`mysql`](https://hub.docker.com/_/mysql) container, which is still updated (and already supported)

**Comment by vahidalvandi** [comment]
> [`mysql/mysql-server`](https://hub.docker.com/r/mysql/mysql-server) I agree does seem to be a container which isn't picked up.
> 
> However, it looks like those containers haven't been updated in "a year", so I'd recommend moving away to the [`mysql`](https://hub.docker.com/_/mysql) container, which is still updated (and already supported)

please add support [mysql/mysql-server](https://hub.docker.com/r/mysql/mysql-server)

**Comment by vahidalvandi** [comment]
so i changed to mysql:8.0

**Comment by RealOrangeOne** [comment]
None of the tags in `mysql/mysql-server` have been updated in over a year - I'm keen not to add support for a clearly-deprecated container.

Did changing to `mysql:8.0` work for you?
