### ISSUE TITLE
please add filename with weekday

### ISSUE THREAD

**Issue by vahidalvandi** [RealOrangeOne/docker-db-auto-backup#69]
for example docker-msyql-db-friday.gzip  , docker-msyql-db-*.gzip

**Comment by RealOrangeOne** [comment]
Filenames currently don't store any date information. This is intentional, as versioning should be handled by an external tool (eg `restic`, ZFS snapshots). Adding weekdays is a major change to this, and requires configuration for rotation, which adds complexity.
