### ISSUE TITLE
Backups don't run if using full container name. 

### ISSUE THREAD

**Issue by DelusionalAI** [RealOrangeOne/docker-db-auto-backup#71]
I've been using Podman in place of Docker, but Podman requires the full container location, i.e. `docker.io/library/postgres`, instead of the short form `Postgres` or even `library/postgres`.

When running the python script, the name of the container returns as `['docker.io/library/postgres']` instead of `['postgres']`, this cases get_backup_provider to return none instead of the Postgres provider. 

I was able to get it working locally by changing `patterns=["postgres", "tensorchord/pgvecto-rs", "nextcloud/aio-postgresql"]` to `patterns=["*postgres", "tensorchord/pgvecto-rs", "nextcloud/aio-postgresql"]` but I imagine something would need to be changed for SQL as well, and while it works for me I'm not sure if there are other containers that would cause an issue with.

**Comment by DelusionalAI** [comment]
This still didn't quite fix it for my use case. The container name now comes across as `{'library/postgres'}` for my tests which doesn't match.

**Comment by RealOrangeOne** [comment]
Damn - it's because they have components of the path which aren't part of the container name. Might need some special-casing for dockerhub.
